# TODO:
# * validate env and paths
# * make non nixos paths optional (/etc/static)
# * use library to auto generate `system` and auto load `NIX_FRAGMENT`
# * auto load NIX_* path and other env's generated by devshell (required by wrapped programs eg c++ compilers)
# * optional `.flake.nix` file that merges with this flake file for personal use
# * generate `/etc/passwd`
{
    description = "Base development project flake with sandboxing";

    outputs = { self, nixpkgs }: let
        system = "x86_64-linux";
        pkgs = import nixpkgs { inherit system; };
    in {
        devShells.${system}.default = pkgs.mkShell {
            packages = [];

            shellHook = /*bash*/ ''
                NIX_FRAGMENT="default"
                EMU_DIR="$PWD/.devshells"
                EMU_DIR_ROOT="$EMU_DIR/efs-root"
                EMU_DIR_HOME="$EMU_DIR_ROOT/home/$USER"
                PROGRAM="$SHELL"
                PROGRAM_ARGS=()
                BWRAP_ARGS=(
                    \
                    --unshare-all \
                    --clearenv \
                    --die-with-parent \
                    --chdir "$PWD" \
                    \
                    --setenv USER "$USER" \
                    --setenv HOME "$HOME" \
                    --setenv PATH "$PATH" \
                    --setenv LANG "$LANG" \
                    --setenv TERM "$TERM" \
                    \
                    --bind "$EMU_DIR_ROOT" "/" \
                    --dev /dev                 \
                    --proc /proc               \
                    --tmpfs /tmp               \
                    \
                    --share-net                                   \
                    --ro-bind /etc/resolv.conf /etc/resolv.conf   \
                    --ro-bind /etc/ssl /etc/ssl                   \
                    --ro-bind /etc/static/ssl /etc/static/ssl     \
                    \
                    --ro-bind "/nix/store" "/nix/store"           \
                    --ro-bind /bin /bin                           \
                    --ro-bind /usr /usr                           \
                    --ro-bind /lib64 /lib64                       \
                    \
                    --bind "$EMU_DIR_HOME" "$HOME"                \
                    --bind "$PWD" "$PWD"                          \
                    --ro-bind "$PWD/flake.nix" "$PWD/flake.nix"   \
                    --ro-bind "$PWD/flake.lock" "$PWD/flake.lock" \
                    \
                )

                if [[ ! -d "$EMU_DIR_HOME" ]]; then
                    mkdir -p "$EMU_DIR_HOME"
                fi

                readarray -d ':' -t nixpaths <<< "$PATH"
                for nixpath in "''${nixpaths[@]}"; do
                    if [[ -e "$nixpath" ]]; then
                        BWRAP_ARGS+=(--ro-bind "$nixpath" "$nixpath")
                    fi
                done

                if [[ -f ./.devshellshook.sh ]]; then
                    BWRAP_ARGS+=(--ro-bind "$PWD/.devshellshook.sh" "$PWD/.devshellshook.sh")
                    source ./.devshellshook.sh
                fi

                exec ${pkgs.bubblewrap}/bin/bwrap \
                    "''${BWRAP_ARGS[@]}" \
                    -- \
                    "$PROGRAM" \
                    "''${PROGRAM_ARGS[@]}"
            '';
        };
    };

    inputs = {
        nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    };
}
